# CI on Windows via appveyor
# This file was based on Olivier Grisel's python-appveyor-demo

environment:

  global:
      PYTHON: "C:\\conda"
      PYTHON_ARCH: "64"
      CONDA_CHANNELS: "conda-forge"

  matrix:
      - PYTHON_VERSION: "3.7"
        CONDA_DEPENDENCIES: "numpy scipy setuptools pytest coverage pytest-cov pytest-sugar pytest-faulthandler cython coveralls freetype-py numpydoc meshio"
        PIP_DEPENDENCIES: "pyopengltk"

platform:
    -x64

install:

  # Get git submodules (not done by appveyor by default)
  - "git submodule update --init --recursive"

  # Install OpenGL
  - "git clone --depth 1 git://github.com/vtkiorg/gl-ci-helpers.git"
  - "powershell gl-ci-helpers/appveyor/install_opengl.ps1"

  # Install conda using ci-helpers. More information about ci-helpers can
  # be found here: https://github.com/astropy/ci-helpers
  - "git clone git://github.com/astropy/ci-helpers.git"
  - "rm ci-helpers/test_env.py"
  - "powershell ci-helpers/appveyor/install-miniconda.ps1"

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Switch to test environment
  - "activate test"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Install vispy
  - "python setup.py develop"
  - "python -c \"import vispy; print(vispy.sys_info())\""

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  # Run the project tests (don't do examples because they are too slow)
  - "python make test unit"

on_success:
  - "coveralls"
