[build-system]
requires = [
    "wheel",
    "setuptools>=30.3.0",
    "setuptools_scm",
    # Use these when setuptools>=42 is more widely available
    # "setuptools>=42",
    # "setuptools_scm[toml]>=3.4",
    "setuptools_scm_git_archive",
    "Cython>=0.29.2",
    "numpy; python_version=='2.7'",
    "numpy==1.13.3; python_version=='3.5'",
    "numpy==1.13.3; python_version=='3.6'",
    "numpy==1.14.5; python_version=='3.7'",
    "numpy==1.17.3; python_version=='3.8'",
]

[tools.setuptools_scm]
write_to = "vispy/version.py"
